In [ ]:
# Data Science for Medicine and Biology
#
# Nezu Life Sciences
#
# Feel free to modify, redistribute and above all,
# create something with this code.
#
# Tiago Lopes, PhD
# March 2024

import numpy as np

# Python list of patient ages
patient_ages_list = [29, 35, 46, 52, 38]

# Convert to a NumPy array for efficient computation
patient_ages_array = np.array(patient_ages_list)

print(patient_ages_array)

[29 35 46 52 38]


In [ ]:
# Recovery times in days for 5 patients
recovery_times = np.array([5, 7, 3, 4, 6])

print(recovery_times)

[5 7 3 4 6]


In [ ]:
# Add a new recovery time
recovery_times = np.append(recovery_times, 8)
print(recovery_times)

# Remove an outlier
recovery_times = np.delete(recovery_times, [2])
print(recovery_times)

# Sort the recovery times
recovery_times = np.sort(recovery_times)

print(recovery_times)

[5 7 3 4 6 8]
[5 7 4 6 8]
[4 5 6 7 8]


In [ ]:
# Simulated gene expression data for 200 samples across 5000 genes
gene_expression_data = np.random.rand(200, 5000)

print(gene_expression_data.shape)

(200, 5000)


In [ ]:
print(gene_expression_data)

[[0.27640969 0.38947591 0.30981876 ... 0.86204437 0.79581158 0.24028972]
 [0.35543121 0.9626672  0.41483829 ... 0.97901741 0.01267318 0.55381022]
 [0.73727491 0.84258493 0.01771031 ... 0.28950518 0.33145379 0.06796359]
 ...
 [0.73928752 0.01961793 0.08996656 ... 0.20270526 0.01540128 0.26542014]
 [0.90840226 0.24846658 0.90554345 ... 0.70608061 0.80416174 0.13223595]
 [0.38694703 0.66774549 0.91117477 ... 0.73181533 0.37538491 0.83891723]]


In [ ]:
# Simulating blood pressure readings for 5 patients over 6 days
bp_readings = np.arange(30)

print("Before reshaping")
print(bp_readings)

bp_readings = bp_readings.reshape(5, 6)

print("After reshaping")
print(bp_readings)

Before reshaping
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
After reshaping
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [ ]:
# Extract data for the third patient
third_patient_data = bp_readings[2, :]
print("Third patient:")
print(third_patient_data)

# Compare the first and second blood pressure readings for all patients
first_second_parameters = bp_readings[:, :2]

print("First and second measurements:")
print(first_second_parameters)

Third patient:
[12 13 14 15 16 17]
First and second measurements:
[[ 0  1]
 [ 6  7]
 [12 13]
 [18 19]
 [24 25]]


In [ ]:
# Pre-treatment and post-treatment biomarker levels
pre_treatment = np.array([4.5, 5.0, 5.5])
post_treatment = np.array([5.0, 5.5, 6.0])

increase = post_treatment - pre_treatment

print(increase)

[0.5 0.5 0.5]


In [ ]:
# Heights (in meters) and weights (in kilograms) of 5 patients
heights = np.array([1.75, 1.8, 1.65, 1.9, 1.74])
weights = np.array([70, 80, 60, 90, 75])

bmis = weights / heights**2

print(bmis)

[22.85714286 24.69135802 22.03856749 24.93074792 24.77209671]


In [ ]:
mutations = np.array(['A', 'B', 'A', 'C', 'B', 'A', 'D', 'A'])

unique_mutations = np.unique(mutations)

print(unique_mutations)

['A' 'B' 'C' 'D']


In [ ]:
mutations = np.array(['A', 'B', 'A', 'C', 'B', 'A', 'D', 'A'])

unique_mutations, counts = np.unique(mutations, return_counts=True)

print(counts)

[4 2 1 1]


In [ ]:
# Simulating the response of 10 patients to a medication
patient_responses = np.random.randint(0, 11, 10)

print(patient_responses)

[ 8  2  3 10  3  2  2  2  5  4]


In [ ]:
# Saving the processed genetic data array
np.save('processed_patient_responses.npy', patient_responses)

# Loading the genetic data array in a new session
loaded_genetic_data = np.load('processed_patient_responses.npy')

In [ ]:
# Today's question

myArray = np.ones(15).reshape(3,5)

randomInt = np.random.randint(0, 100, 15)
randomInt = randomInt.reshape(3,5)

myArray = myArray + randomInt

print(myArray)

[[58. 23. 28. 23. 35.]
 [24. 23. 66. 59. 62.]
 [93. 30. 32. 18. 67.]]
